### PR TITLE
Implement logged out users verification based on email OR first & last name

### PR DESCRIPTION
**Pull request by MacWarrior**

### CODE REVIEW

**Review by ashrafulsarkar — APPROVED** [review]

**Comment by ashrafulsarkar** [comment]
Manually added your code.

Thanks for fixed.

**Comment by ashrafulsarkar** [comment]
please send your **wordpress.org** username.

Thanks

**Comment by MacWarrior** [comment]
Hello @ashrafulsarkar, 

I created a profile on wordpress.org : https://profiles.wordpress.org/oxygenz/

Best regards,
MacWarrior.

**Comment by ashrafulsarkar** [comment]
Thanks For your contribution.

Best regards,
Ashraful Sarkar Naiem.

**Pull request closed without merging**
